const storageKey='sarmart-records-v2', contactsKey='sarmart-contacts-v1', stockKey='sarmart-out-of-stock-v1', stockPendingKey='sarmart-stock-pending-v1', assistantLoginsKey='sarmart-assistant-logins-v1', reconciliationKey='sarmart-reconciliation-v1', sessionKey='sarmart-current-user', googleTokenKey='sarmart-google-sheet-token', deletedKey='sarmart-pending-deletes-v1', pendingWritesKey='sarmart-pending-writes-v1';
const GOOGLE_SCRIPT_URL='https://script.google.com/macros/s/AKfycbynbO5vq2RCxxWZP4v81pLp76bsLQ6Rv5dBgz3RLFQKCHpxpo5PO5eGAQWNHwEIUENduQ/exec';
const accounts={admin:{username:'sam',password:'123',label:'Administrator'}};
const categories=['Inventory / stock','Rent','Utilities','Phone & internet','Transport','Salaries & wages','Marketing','Office supplies','Repairs & maintenance','Professional services','Taxes & licences','Other'];
const readJson=(storage,key,fallback)=>{try{const value=JSON.parse(storage.getItem(key)||'null');return value??fallback;}catch{return fallback;}};
let records=readJson(localStorage,storageKey,[]), contacts=readJson(localStorage,contactsKey,[]), outOfStock=readJson(localStorage,stockKey,[]), assistantLogins=readJson(localStorage,assistantLoginsKey,[]), reconciliation=readJson(localStorage,reconciliationKey,{}), currentUser=readJson(sessionStorage,sessionKey,null), pendingDeletes=new Set(readJson(localStorage,deletedKey,[])), pendingWrites=new Set(readJson(localStorage,pendingWritesKey,[])), pendingStockWrites=new Set(readJson(localStorage,stockPendingKey,[])), cashMode='out', undoHistory=[], redoHistory=[],newStockPhoto='',editStockPhoto='';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const isStockManager=()=>currentUser?.role==='admin'||String(currentUser?.role||'').startsWith('stock-assistant-');
const isStockAssistant=()=>String(currentUser?.role||'').startsWith('stock-assistant-');
const loginAccounts=()=>[{role:'admin',...accounts.admin},...assistantLogins.map(login=>({role:`${login.access==='stock'?'stock-assistant':'assistant'}-${login.id}`,username:login.username,label:login.access==='stock'?'Stock Assistant':'Assistant'}))];
const money=new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0});
const today=()=>new Date().toISOString().slice(0,10); const dateText=value=>value?new Date(`${value}T00:00:00`).toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'}):'—';
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const typeName=type=>type==='receivable'?'Receivable':type==='payable'?'Payable':'Expense / Cash Out';
const isDue=(r,days=0)=>r.due&&r.due<=new Date(Date.now()+days*86400000).toISOString().slice(0,10);
function paid(r){return Math.min(Math.abs(Number(r.paidAmount||0)),Math.abs(Number(r.amount||0)));} function outstanding(r){const amount=Number(r.amount||0);return amount>=0?amount-paid(r):amount+paid(r);}
function statusOf(r){if(r.type==='expense')return 'recorded'; if(Math.abs(outstanding(r))<0.001)return 'paid'; if(paid(r)>0)return 'part-paid'; return isDue(r,-1)?'overdue':'open';}
function paymentEntries(r){let entries=r.payments;if(typeof entries==='string'){try{entries=JSON.parse(entries);}catch{entries=[];}}return Array.isArray(entries)&&entries.length?entries:(paid(r)?[{amount:paid(r),date:r.lastPaymentDate||r.date}]:[]);}
function paymentsThisMonth(r){const now=new Date();return paymentEntries(r).filter(p=>{const d=new Date(`${p.date}T00:00:00`);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();}).reduce((sum,p)=>sum+Number(p.amount||0),0);}
function noteEntries(r){let entries=r.noteEntries;if(typeof entries==='string'){try{entries=JSON.parse(entries);}catch{entries=[];}}if(Array.isArray(entries)&&entries.length)return entries;return String(r.notes||'').split(' · ').filter(Boolean).map(text=>({text,date:r.date,time:r.time,enteredBy:r.enteredBy||'Imported record'}));}
function noteMeta(entry,r){const date=entry.date||r.date,time=entry.time||r.time||'—',person=entry.enteredBy||r.enteredBy||'Imported record',day=date?new Date(`${date}T00:00:00`).toLocaleDateString('en-KE',{weekday:'long',day:'numeric',month:'short',year:'numeric'}):'Date not recorded';return `${day} · ${time} · Entered by ${person}`;}
function stateSnapshot(){return JSON.stringify({records,contacts});}let historyBaseline=stateSnapshot();
function updateHistoryButtons(){$('#undo-action').disabled=!undoHistory.length;$('#redo-action').disabled=!redoHistory.length;}
function save(track=true){const current=stateSnapshot();if(track&&current!==historyBaseline){undoHistory.push(historyBaseline);if(undoHistory.length>30)undoHistory.shift();redoHistory=[];}historyBaseline=current;localStorage.setItem(storageKey,JSON.stringify(records));localStorage.setItem(contactsKey,JSON.stringify(contacts));localStorage.setItem(stockKey,JSON.stringify(outOfStock));localStorage.setItem(deletedKey,JSON.stringify([...pendingDeletes]));localStorage.setItem(pendingWritesKey,JSON.stringify([...pendingWrites]));localStorage.setItem(stockPendingKey,JSON.stringify([...pendingStockWrites]));render();updateHistoryButtons();}
function restoreHistory(target){const before=JSON.parse(historyBaseline),after=JSON.parse(target),beforeMap=new Map(before.records.map(r=>[r.id,r])),afterMap=new Map(after.records.map(r=>[r.id,r]));records=after.records;contacts=after.contacts;for(const [id,record] of afterMap){if(!beforeMap.has(id)){pendingDeletes.delete(id);sync('create',{record},true);}else if(JSON.stringify(record)!==JSON.stringify(beforeMap.get(id)))sync('update',{record},true);}for(const id of beforeMap.keys())if(!afterMap.has(id))pendingDeletes.add(id);historyBaseline=target;save(false);syncPendingDeletes();}
function undo(){if(!undoHistory.length)return;const target=undoHistory.pop();redoHistory.push(historyBaseline);restoreHistory(target);toast('Last change undone');}
function redo(){if(!redoHistory.length)return;const target=redoHistory.pop();undoHistory.push(historyBaseline);restoreHistory(target);toast('Change redone');}
function token(){return localStorage.getItem(googleTokenKey)||'';} function setSync(text,on=false){$('#sync-status').textContent=text;$('#sync-status').classList.toggle('connected',on);}
async function googleRequest(action,payload={}){if(!token())throw Error('Enter the private API token.');const isList=['list','listContacts','listStock','getSessionVersion'].includes(action);const url=isList?`${GOOGLE_SCRIPT_URL}?token=${encodeURIComponent(token())}&action=${action}`:GOOGLE_SCRIPT_URL;const options=isList?{}:{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({token:token(),action,...payload})};const response=await fetch(url,options);const result=await response.json();if(!result.ok)throw Error(result.error||'Google Sheet request failed.');return result.data;}
function fingerprint(items){return JSON.stringify(items.map(item=>Object.keys(item).sort().reduce((out,key)=>{out[key]=item[key];return out;},{})).sort((a,b)=>String(a.id).localeCompare(String(b.id))));}
async function pullAll(quiet=false){if(!token())return {ok:false,message:'Enter the private API token first.'};if(!quiet)setSync('Syncing…');try{const cloud=await googleRequest('list');const parseList=value=>{if(typeof value!=='string')return value||[];try{return JSON.parse(value)||[];}catch{return [];}};const remote=cloud.map(r=>({...r,amount:Number(r.amount),paidAmount:Number(r.paidAmount||0),payments:parseList(r.payments),noteEntries:parseList(r.noteEntries)})).filter(r=>!pendingDeletes.has(r.id));const localPending=records.filter(r=>pendingWrites.has(r.id));const nextRecords=[...remote.filter(r=>!pendingWrites.has(r.id)),...localPending];let nextContacts=contacts,nextStock=outOfStock;try{nextContacts=await googleRequest('listContacts');}catch{}try{const remoteStock=await googleRequest('listStock');nextStock=[...remoteStock.filter(item=>!pendingStockWrites.has(item.id)),...outOfStock.filter(item=>pendingStockWrites.has(item.id))];}catch{}const changed=fingerprint(records)!==fingerprint(nextRecords)||fingerprint(contacts)!==fingerprint(nextContacts)||fingerprint(outOfStock)!==fingerprint(nextStock);if(changed&&!$('#record-dialog').open&&!$('#contact-dialog').open){records=nextRecords;contacts=nextContacts;outOfStock=nextStock;historyBaseline=stateSnapshot();localStorage.setItem(storageKey,JSON.stringify(records));localStorage.setItem(contactsKey,JSON.stringify(contacts));localStorage.setItem(stockKey,JSON.stringify(outOfStock));render();updateHistoryButtons();}if(!quiet)setSync('Google Sheet synced',true);return {ok:true};}catch(error){if(!quiet)setSync('Sheet unavailable');return {ok:false,message:error.message||'Browser could not reach Google Sheets.'};}}
async function sync(action,payload,quiet=false){const recordId=payload?.record?.id;if(recordId){pendingWrites.add(recordId);localStorage.setItem(pendingWritesKey,JSON.stringify([...pendingWrites]));}if(!token())return false;try{await googleRequest(action,payload);if(recordId){pendingWrites.delete(recordId);localStorage.setItem(pendingWritesKey,JSON.stringify([...pendingWrites]));}setSync('Google Sheet synced',true);return true;}catch{setSync('Saved on this device');if(!quiet)toast('Saved locally. Sheet sync will retry.');return false;}}
async function syncStock(action,item){pendingStockWrites.add(item.id);localStorage.setItem(stockPendingKey,JSON.stringify([...pendingStockWrites]));if(!token())return false;try{await googleRequest(action,{item});pendingStockWrites.delete(item.id);localStorage.setItem(stockPendingKey,JSON.stringify([...pendingStockWrites]));setSync('Google Sheet synced',true);return true;}catch{setSync('Saved on this device');toast('Saved on this device.');return false;}}
async function syncPendingDeletes(){for(const id of [...pendingDeletes]){if(await sync('delete',{id},true)){pendingDeletes.delete(id);save();}}}
async function verifyRemoteSession(){if(!currentUser||!token())return;try{const session=await googleRequest('getSessionVersion'),version=String(session.version||'1');if(!currentUser.sessionVersion){currentUser.sessionVersion=version;sessionStorage.setItem(sessionKey,JSON.stringify(currentUser));return;}if(currentUser.sessionVersion!==version){sessionStorage.removeItem(sessionKey);currentUser=null;$('#login-form').reset();updateLogin();toast('You were signed out by the Administrator.');}}catch{}}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show-toast');setTimeout(()=>el.classList.remove('show-toast'),2600);}
function monthRecord(r){const d=new Date(`${r.date}T00:00:00`),n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear();}
function filtered(type){let out=records.filter(r=>r.type===type);const search=$(`[data-filter="${type}"]`)?.value.trim().toLowerCase()||'';const status=$(`[data-status-filter="${type}"]`)?.value||'';const category=$('[data-category-filter]')?.value||'',from=$(`[data-date-from="${type}"]`)?.value||'',to=$(`[data-date-to="${type}"]`)?.value||'',min=$(`[data-min-total="${type}"]`)?.value,max=$(`[data-max-total="${type}"]`)?.value,sort=$(`[data-sort="${type}"]`)?.value||'newest';if(search)out=out.filter(r=>`${r.name} ${r.party} ${r.category} ${r.notes}`.toLowerCase().includes(search));if(status)out=out.filter(r=>statusOf(r)===status);if(category)out=out.filter(r=>r.category===category);if(from)out=out.filter(r=>String(r.createdAt||r.date||'').slice(0,10)>=from);if(to)out=out.filter(r=>String(r.createdAt||r.date||'').slice(0,10)<=to);if(min!=='')out=out.filter(r=>Math.abs(Number(r.amount||0))>=Number(min));if(max!=='')out=out.filter(r=>Math.abs(Number(r.amount||0))<=Number(max));const label=r=>String(r.party||r.name||'').toLowerCase();return out.sort((a,b)=>sort==='a-z'?label(a).localeCompare(label(b)):sort==='z-a'?label(b).localeCompare(label(a)):sort==='high-low'?Math.abs(Number(b.amount||0))-Math.abs(Number(a.amount||0)):sort==='low-high'?Math.abs(Number(a.amount||0))-Math.abs(Number(b.amount||0)):`${b.date||''}${b.createdAt||b.id||''}`.localeCompare(`${a.date||''}${a.createdAt||a.id||''}`));}
function actions(r){if(currentUser?.role!=='admin')return '';if(r.type==='expense')return `<button class="row-action" data-edit="${r.id}">Edit</button><button class="delete-btn" data-delete="${r.id}">Delete</button>`;const payButton=statusOf(r)!=='paid'&&outstanding(r)>0?`<button class="account-icon pay-icon" data-payment="${r.id}" title="Record payment" aria-label="Record payment">✓</button>`:'';return `${payButton}<button class="account-icon edit-icon" data-edit="${r.id}" title="Edit entry" aria-label="Edit entry">✎</button><button class="account-icon delete-icon" data-delete="${r.id}" title="Delete entry" aria-label="Delete entry">×</button>`;}
function statusBadge(r){const status=statusOf(r);return `<span class="status ${status}">${status.replace('-',' ')}</span>`;}
function tableRow(r){const color=/^#[0-9a-f]{6}$/i.test(r.color||'')?r.color:'';return `<div class="record-row" data-entry-id="${esc(r.id)}" data-color-record="${esc(r.id)}" style="--entry-highlight:${color}"><div><strong>${esc(r.name||'Untitled record')}</strong><span>${esc(r.type==='expense'?(r.category||'Other'):(r.party||'No contact'))}</span></div><span>${dateText(r.date)}</span><span>${r.type==='expense'?'—':dateText(r.due)}</span><div><strong class="amount ${r.type}">${money.format(r.amount)}</strong><span>${r.type==='expense'?'Recorded':`${money.format(paid(r))} paid`}</span></div><div>${statusBadge(r)}</div><div class="row-actions">${actions(r)}</div></div>`;}
function accountCard(r){const receivable=r.type==='receivable',balance=outstanding(r),sign=receivable?(balance>=0?'+':'-'):(balance>=0?'-':'+'),party=r.party||r.name||'No contact',detail=[dateText(r.date),r.time||'—',r.due?`Due ${dateText(r.due)}`:'No due date'].filter(Boolean).join(' · '),notes=noteEntries(r),color=/^#[0-9a-f]{6}$/i.test(r.color||'')?r.color:'';return `<article class="account-card" data-entry-id="${esc(r.id)}" data-color-record="${esc(r.id)}" style="--entry-highlight:${color}"><div class="account-info"><strong>${esc(party)}</strong><span>${esc(detail)}</span>${notes.length?`<details class="account-notes"><summary>Notes (${notes.length}) <b>⌄</b></summary><div>${notes.map(note=>`<div class="note-history"><span>${esc(note.text)}</span><small>${esc(noteMeta(note,r))}</small></div>`).join('')}</div></details>`:''}</div><div class="account-money"><strong class="amount ${r.type}">${sign}${money.format(Math.abs(balance))}</strong></div><div class="account-actions">${actions(r)}</div></article>`;}
function renderList(type){const items=filtered(type),target=$(`#${type}-list`);if(!items.length){target.innerHTML=`<div class="empty">No ${type==='expense'?'cash-out records':`${type}s`} yet.</div>`;return;}target.innerHTML=type==='expense'?`<div class="list-head"><span>Description</span><span>Date</span><span>Due date</span><span>Amount</span><span>Status</span><span></span></div>${items.map(tableRow).join('')}`:items.map(accountCard).join('');}
function renderDashboard(){const rec=records.filter(r=>r.type==='receivable'),pay=records.filter(r=>r.type==='payable'),expenses=records.filter(r=>r.type==='expense'),directCashOut=expenses.filter(monthRecord).reduce((s,r)=>s+Number(r.amount),0),supplierPayments=pay.reduce((s,r)=>s+paymentsThisMonth(r),0),monthExpenses=directCashOut+supplierPayments,monthIncome=rec.reduce((s,r)=>s+paymentsThisMonth(r),0);$('#receivable-total').textContent=money.format(rec.reduce((s,r)=>s+outstanding(r),0));$('#payable-total').textContent=money.format(pay.reduce((s,r)=>s+outstanding(r),0));$('#expense-total').textContent=money.format(monthExpenses);$('#expense-count').textContent=`${expenses.length} cash-out entries recorded`;$('#net-total').textContent=money.format(monthIncome-monthExpenses);const recent=records.filter(r=>r.date===today()).sort((a,b)=>String(b.createdAt||b.id).localeCompare(String(a.createdAt||a.id)));$('#recent-list').innerHTML=recent.length?recent.map(r=>`<button class="activity-row activity-link" data-open-entry="${esc(r.id)}" data-open-type="${r.type}" type="button"><div class="record-icon ${r.type}">${r.type==='expense'?'↓':r.type==='receivable'?'↑':'→'}</div><div><h3>${esc(r.name||'Untitled record')}</h3><p>${typeName(r.type)} · ${r.type==='expense'?r.category||'Other':r.party||'No contact'}</p></div><div class="amount ${r.type}">${money.format(r.amount)}</div></button>`).join(''):'<div class="empty">No entries recorded today.</div>';const watch=[...rec,...pay].filter(r=>statusOf(r)!=='paid'&&r.due&&isDue(r,7)).sort((a,b)=>a.due.localeCompare(b.due));$('#alerts-list').innerHTML=watch.length?watch.map(r=>`<div class="alert-row ${statusOf(r)==='overdue'?'overdue-alert':''}"><div><strong>${esc(r.name||r.party||'Untitled record')}</strong><span>${typeName(r.type)} · Due ${dateText(r.due)}</span></div><div>${statusBadge(r)} <strong>${money.format(outstanding(r))}</strong></div></div>`).join(''):'<div class="empty small-empty">No due-date reminders right now.</div>';}
function renderContacts(){const query=$('[data-contact-search]')?.value.toLowerCase()||'',items=contacts.filter(c=>`${c.name} ${c.type} ${c.phone} ${c.email}`.toLowerCase().includes(query));$('#contacts-list').innerHTML=items.length?`<div class="list-head contact-head"><span>Name</span><span>Type</span><span>Phone</span><span>Email</span></div>${items.map(c=>`<div class="contact-row"><strong>${esc(c.name)}</strong><span>${esc(c.type)}</span><span>${esc(c.phone||'—')}</span><span>${esc(c.email||'—')}</span></div>`).join('')}`:'<div class="empty">No saved contacts yet.</div>';const names=[...new Set([...contacts.map(c=>c.name),...records.map(r=>r.party)].map(name=>String(name||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));$('#contact-options').innerHTML=names.map(name=>`<option value="${esc(name)}"></option>`).join('');}
function renderReports(){const expenses=records.filter(r=>r.type==='expense'&&monthRecord(r)),income=records.filter(r=>r.type==='receivable').reduce((s,r)=>s+paymentsThisMonth(r),0),directCashOut=expenses.reduce((s,r)=>s+Number(r.amount),0),supplierPayments=records.filter(r=>r.type==='payable').reduce((s,r)=>s+paymentsThisMonth(r),0),cash=directCashOut+supplierPayments;$('#report-income').textContent=money.format(income);$('#report-expense').textContent=money.format(cash);$('#report-net').textContent=money.format(income-cash);const grouped=Object.entries(expenses.reduce((a,r)=>{a[r.category||'Other']=(a[r.category||'Other']||0)+Number(r.amount);return a;},{}));$('#category-report').innerHTML=grouped.length?grouped.sort((a,b)=>b[1]-a[1]).map(([name,value])=>`<div class="report-row"><span>${esc(name)}</span><strong>${money.format(value)}</strong></div>`).join(''):'<div class="empty small-empty">No cash-out records this month.</div>';const balance=[...records.filter(r=>r.type==='receivable'||r.type==='payable')].filter(r=>statusOf(r)!=='paid');$('#balance-report').innerHTML=balance.length?balance.map(r=>`<div class="report-row"><span>${esc(r.party||r.name||'Untitled')} <small>${typeName(r.type)}</small></span><strong>${money.format(outstanding(r))}</strong></div>`).join(''):'<div class="empty small-empty">No unpaid balances.</div>';}
function renderReports(){const expenses=records.filter(r=>r.type==='expense'&&monthRecord(r)),income=records.filter(r=>r.type==='receivable').reduce((s,r)=>s+paymentsThisMonth(r),0),directCashOut=expenses.reduce((s,r)=>s+Number(r.amount),0),supplierPayments=records.filter(r=>r.type==='payable').reduce((s,r)=>s+paymentsThisMonth(r),0),cash=directCashOut+supplierPayments;$('#report-income').textContent=money.format(income);$('#report-expense').textContent=money.format(cash);$('#report-net').textContent=money.format(income-cash);const grouped=Object.entries(expenses.reduce((a,r)=>{a[r.category||'Other']=(a[r.category||'Other']||0)+Number(r.amount);return a;},{}));$('#category-report').innerHTML=gr
