const storageKey='sarmart-records-v2', contactsKey='sarmart-contacts-v1', sessionKey='sarmart-current-user', googleTokenKey='sarmart-google-sheet-token';
const GOOGLE_SCRIPT_URL='https://script.google.com/macros/s/AKfycbzUryWUwjSc50PBidhNvRa8OqCuUOe1PLztWiSbVRTk-zEvjC6pFwPd_IPMHg2COojQHQ/exec';
const accounts={admin:{username:'sammwaww@gmail.com',password:'admin123',label:'Administrator'},assistant:{username:'assistant',password:'assistant123',label:'Assistant'}};
const categories=['Inventory / stock','Rent','Utilities','Phone & internet','Transport','Salaries & wages','Marketing','Office supplies','Repairs & maintenance','Professional services','Taxes & licences','Other'];
let records=JSON.parse(localStorage.getItem(storageKey)||'[]'), contacts=JSON.parse(localStorage.getItem(contactsKey)||'[]'), currentUser=JSON.parse(sessionStorage.getItem(sessionKey)||'null');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0});
const today=()=>new Date().toISOString().slice(0,10); const dateText=value=>value?new Date(`${value}T00:00:00`).toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'}):'—';
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const typeName=type=>type==='receivable'?'Receivable':type==='payable'?'Payable':'Expense / Cash Out';
const isDue=(r,days=0)=>r.due&&r.due<=new Date(Date.now()+days*86400000).toISOString().slice(0,10);
function paid(r){return Math.min(Number(r.paidAmount||0),Number(r.amount||0));} function outstanding(r){return Math.max(0,Number(r.amount||0)-paid(r));}
function statusOf(r){if(r.type==='expense')return 'recorded'; if(outstanding(r)<=0)return 'paid'; if(paid(r)>0)return 'part-paid'; return isDue(r,-1)?'overdue':'open';}
function save(){localStorage.setItem(storageKey,JSON.stringify(records)); localStorage.setItem(contactsKey,JSON.stringify(contacts));render();}
function token(){return localStorage.getItem(googleTokenKey)||'';} function setSync(text,on=false){$('#sync-status').textContent=text;$('#sync-status').classList.toggle('connected',on);}
async function googleRequest(action,payload={}){if(!token())throw Error('Enter the private API token.');const isList=action==='list'||action==='listContacts';const url=isList?`${GOOGLE_SCRIPT_URL}?token=${encodeURIComponent(token())}&action=${action}`:GOOGLE_SCRIPT_URL;const options=isList?{}:{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({token:token(),action,...payload})};const response=await fetch(url,options);const result=await response.json();if(!result.ok)throw Error(result.error||'Google Sheet request failed.');return result.data;}
function fingerprint(items){return JSON.stringify(items.map(item=>Object.keys(item).sort().reduce((out,key)=>{out[key]=item[key];return out;},{})).sort((a,b)=>String(a.id).localeCompare(String(b.id))));}
async function pullAll(quiet=false){if(!token())return {ok:false,message:'Enter the private API token first.'};if(!quiet)setSync('Syncing…');try{const cloud=await googleRequest('list');const nextRecords=cloud.map(r=>({...r,amount:Number(r.amount),paidAmount:Number(r.paidAmount||0)}));let nextContacts=contacts;try{nextContacts=await googleRequest('listContacts');}catch{}const changed=fingerprint(records)!==fingerprint(nextRecords)||fingerprint(contacts)!==fingerprint(nextContacts);if(changed&&!$('#record-dialog').open&&!$('#contact-dialog').open){records=nextRecords;contacts=nextContacts;localStorage.setItem(storageKey,JSON.stringify(records));localStorage.setItem(contactsKey,JSON.stringify(contacts));render();}if(!quiet)setSync('Google Sheet synced',true);return {ok:true};}catch(error){if(!quiet)setSync('Sheet unavailable');return {ok:false,message:error.message||'Browser could not reach Google Sheets.'};}}
async function sync(action,payload){if(!token())return;try{await googleRequest(action,payload);setSync('Google Sheet synced',true);}catch{setSync('Saved on this device');toast('Saved locally. Sheet sync will retry.');}}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show-toast');setTimeout(()=>el.classList.remove('show-toast'),2600);}
function monthRecord(r){const d=new Date(`${r.date}T00:00:00`),n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear();}
function filtered(type){let out=records.filter(r=>r.type===type);const search=$(`[data-filter="${type}"]`)?.value.trim().toLowerCase()||'';const status=$(`[data-status-filter="${type}"]`)?.value||'';const category=$('[data-category-filter]')?.value||'';if(search)out=out.filter(r=>`${r.name} ${r.party} ${r.category}`.toLowerCase().includes(search));if(status)out=out.filter(r=>statusOf(r)===status);if(category)out=out.filter(r=>r.category===category);return out.sort((a,b)=>b.date.localeCompare(a.date));}
function actions(r){if(currentUser?.role!=='admin')return '';if(r.type==='expense')return `<button class="row-action" data-edit="${r.id}">Edit</button><button class="delete-btn" data-delete="${r.id}">Delete</button>`;const payButton=statusOf(r)!=='paid'?`<button class="row-action" data-paid="${r.id}">Mark paid</button>`:'';return `${payButton}<button class="row-action" data-edit="${r.id}">Edit</button><button class="delete-btn" data-delete="${r.id}">Delete</button>`;}
function statusBadge(r){const status=statusOf(r);return `<span class="status ${status}">${status.replace('-',' ')}</span>`;}
function tableRow(r){return `<div class="record-row"><div><strong>${esc(r.name||'Untitled record')}</strong><span>${esc(r.type==='expense'?(r.category||'Other'):(r.party||'No contact'))}</span></div><span>${dateText(r.date)}</span><span>${r.type==='expense'?'—':dateText(r.due)}</span><div><strong class="amount ${r.type}">${money.format(r.amount)}</strong><span>${r.type==='expense'?'Recorded':`${money.format(paid(r))} paid`}</span></div><div>${statusBadge(r)}</div><div class="row-actions">${actions(r)}</div></div>`;}
function renderList(type){const items=filtered(type),target=$(`#${type}-list`);target.innerHTML=items.length?`<div class="list-head"><span>Description</span><span>Date</span><span>Due date</span><span>Amount</span><span>Status</span><span></span></div>${items.map(tableRow).join('')}`:`<div class="empty">No ${type==='expense'?'cash-out records':`${type}s`} yet.</div>`;}
function renderDashboard(){const rec=records.filter(r=>r.type==='receivable'),pay=records.filter(r=>r.type==='payable'),expenses=records.filter(r=>r.type==='expense'),monthExpenses=expenses.filter(monthRecord).reduce((s,r)=>s+Number(r.amount),0),monthIncome=rec.filter(r=>monthRecord(r)).reduce((s,r)=>s+paid(r),0);$('#receivable-total').textContent=money.format(rec.reduce((s,r)=>s+outstanding(r),0));$('#payable-total').textContent=money.format(pay.reduce((s,r)=>s+outstanding(r),0));$('#expense-total').textContent=money.format(monthExpenses);$('#expense-count').textContent=`${expenses.length} entries recorded`;$('#net-total').textContent=money.format(monthIncome-monthExpenses);const recent=records.filter(r=>r.date===today()).sort((a,b)=>String(b.createdAt||b.id).localeCompare(String(a.createdAt||a.id)));$('#recent-list').innerHTML=recent.length?recent.map(r=>`<div class="activity-row"><div class="record-icon ${r.type}">${r.type==='expense'?'↓':r.type==='receivable'?'↑':'→'}</div><div><h3>${esc(r.name||'Untitled record')}</h3><p>${typeName(r.type)} · ${r.type==='expense'?r.category||'Other':r.party||'No contact'}</p></div><div class="amount ${r.type}">${money.format(r.amount)}</div></div>`).join(''):'<div class="empty">No entries recorded today.</div>';const watch=[...rec,...pay].filter(r=>statusOf(r)!=='paid'&&r.due&&isDue(r,7)).sort((a,b)=>a.due.localeCompare(b.due));$('#alerts-list').innerHTML=watch.length?watch.map(r=>`<div class="alert-row ${statusOf(r)==='overdue'?'overdue-alert':''}"><div><strong>${esc(r.name||r.party||'Untitled record')}</strong><span>${typeName(r.type)} · Due ${dateText(r.due)}</span></div><div>${statusBadge(r)} <strong>${money.format(outstanding(r))}</strong></div></div>`).join(''):'<div class="empty small-empty">No due-date reminders right now.</div>';}
function renderContacts(){const query=$('[data-contact-search]')?.value.toLowerCase()||'',items=contacts.filter(c=>`${c.name} ${c.type} ${c.phone} ${c.email}`.toLowerCase().includes(query));$('#contacts-list').innerHTML=items.length?`<div class="list-head contact-head"><span>Name</span><span>Type</span><span>Phone</span><span>Email</span></div>${items.map(c=>`<div class="contact-row"><strong>${esc(c.name)}</strong><span>${esc(c.type)}</span><span>${esc(c.phone||'—')}</span><span>${esc(c.email||'—')}</span></div>`).join('')}`:'<div class="empty">No saved contacts yet.</div>';$('#contact-options').innerHTML=contacts.map(c=>`<option value="${esc(c.name)}"></option>`).join('');}
function renderReports(){const expenses=records.filter(r=>r.type==='expense'&&monthRecord(r)),income=records.filter(r=>r.type==='receivable'&&monthRecord(r)).reduce((s,r)=>s+paid(r),0),cash=expenses.reduce((s,r)=>s+Number(r.amount),0);$('#report-income').textContent=money.format(income);$('#report-expense').textContent=money.format(cash);$('#report-net').textContent=money.format(income-cash);const grouped=Object.entries(expenses.reduce((a,r)=>{a[r.category||'Other']=(a[r.category||'Other']||0)+Number(r.amount);return a;},{}));$('#category-report').innerHTML=grouped.length?grouped.sort((a,b)=>b[1]-a[1]).map(([name,value])=>`<div class="report-row"><span>${esc(name)}</span><strong>${money.format(value)}</strong></div>`).join(''):'<div class="empty small-empty">No cash-out records this month.</div>';const balance=[...records.filter(r=>r.type==='receivable'||r.type==='payable')].filter(r=>statusOf(r)!=='paid');$('#balance-report').innerHTML=balance.length?balance.map(r=>`<div class="report-row"><span>${esc(r.party||r.name||'Untitled')} <small>${typeName(r.type)}</small></span><strong>${money.format(outstanding(r))}</strong></div>`).join(''):'<div class="empty small-empty">No unpaid balances.</div>';}
function render(){renderDashboard();['expense','receivable','payable'].forEach(renderList);renderContacts();renderReports();}
function openRecord(type,id=''){const r=id?records.find(x=>x.id===id):null;$('#record-form').reset();$('#record-id').value=id;$('#record-type').value=type;$('#record-date').value=r?.date||today();$('#record-name').value=r?.name||'';$('#record-category').value=r?.category||'Inventory / stock';$('#record-party').value=r?.party||'';$('#record-amount').value=r?.amount??'';$('#record-due').value=r?.due||'';$('#record-status').value=r?statusOf(r):'open';$('#record-paid').value=r?.paidAmount||0;$('#record-notes').value=r?.notes||'';const expense=type==='expense';$('#category-field').style.display=expense?'grid':'none';$('#party-field').style.display=expense?'none':'grid';$('#due-field').style.display=expense?'none':'grid';$('#payment-fields').style.display=expense?'none':'block';$('#dialog-title').textContent=r?`Edit ${typeName(type).toLowerCase()}`:`Add ${typeName(type).toLowerCase()}`;$('#record-dialog').showModal();}
function editRecord(id){const r=records.find(x=>x.id===id);if(r)openRecord(r.type,id);}
function showView(view,updateLink=true){if(!$('#'+view))view='dashboard';$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===view));$$('.nav-link').forEach(v=>v.classList.toggle('active',v.dataset.view===view));const names={dashboard:'Business overview',expenses:'Expenses / Cash Out',receivables:'Accounts receivable',payables:'Accounts payable',contacts:'Contacts',reports:'Reports'};$('#page-title').textContent=names[view];$('#add-record').style.display=['dashboard','contacts','reports'].includes(view)?'none':'inline-block';$('#add-record').textContent=view==='expenses'?'+ Add cash out':`+ Add ${view.slice(0,-1)}`;if(updateLink&&location.hash!==`#${view}`)history.replaceState(null,'',`#${view}`);window.scrollTo({top:0,behavior:'smooth'});}
function exportCsv(type){const items=type==='report'?records:filtered(type);const rows=[['Type','Description','Category','Contact','Amount','Paid amount','Status','Record date','Due date','Notes'],...items.map(r=>[typeName(r.type),r.name||'',r.category||'',r.party||'',r.amount,paid(r),statusOf(r),r.date,r.due||'',r.notes||''])];const csv=rows.map(row=>row.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`sarmart-${type}-${today()}.csv`;a.click();URL.revokeObjectURL(a.href);}
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i],next=text[i+1];if(char==='"'&&quoted&&next==='"'){field+='"';i++;}else if(char==='"')quoted=!quoted;else if(char===','&&!quoted){row.push(field);field='';}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')i++;row.push(field);if(row.some(v=>v!==''))rows.push(row);row=[];field='';}else field+=char;}row.push(field);if(row.some(v=>v!==''))rows.push(row);return rows;}
function importedType(value){const name=String(value||'').toLowerCase();return name.includes('receivable')?'receivable':name.includes('payable')?'payable':'expense';}
async function importRecords(file,onlyType=''){let rows;if(/\.(xlsx|xls)$/i.test(file.name)){if(!window.XLSX){toast('Excel support is loading. Check your internet connection and try again.');return;}const workbook=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false,dateNF:'yyyy-mm-dd'});}else rows=parseCsv(await file.text());if(rows.length<2){toast('The file has no records to import.');return;}const headers=rows.shift().map(h=>String(h).trim().toLowerCase());const index=name=>headers.indexOf(name);if(index('type')===-1||index('amount')===-1||index('record date')===-1){toast('Use a SARMART export file with Type, Amount, and Record date columns.');return;}const imported=[];for(const row of rows){const amount=Number(String(row[index('amount')]||'').replace(/[^0-9.-]/g,''));const date=String(row[index('record date')]||'');if(!Number.isFinite(amount)||!date)continue;const type=importedType(row[index('type')]);if(onlyType&&type!==onlyType)continue;const record={id:crypto.randomUUID(),type,name:row[index('description')]||'',category:type==='expense'?(row[index('category')]||'Other'):'',party:row[index('contact')]||'',amount,date,due:row[index('due date')]||'',paidAmount:Number(String(row[index('paid amount')]||0).replace(/[^0-9.-]/g,'')),status:(row[index('status')]||'open').toLowerCase(),notes:row[index('notes')]||'',createdAt:new Date().toISOString()};if(record.status==='paid')record.paidAmount=amount;imported.push(record);}if(!imported.length){toast(onlyType?`No ${onlyType} records found in that file.`:'No valid records found in that file.');return;}records.push(...imported);save();imported.forEach(record=>sync('create',{record}));toast(`${imported.length} record${imported.length===1?'':'s'} imported`);}
$('#record-form').addEventListener('submit',e=>{e.preventDefault();const id=$('#record-id').value,type=$('#record-type').value,amount=Number($('#record-amount').value),rawPaid=type==='expense'?0:Number($('#record-paid').value||0),status=type==='expense'?'recorded':$('#record-status').value,paidAmount=status==='paid'?amount:status==='open'?0:Math.min(rawPaid,amount),existing=records.find(r=>r.id===id);const record={id:id||crypto.randomUUID(),type,name:$('#record-name').value.trim(),category:type==='expense'?$('#record-category').value:'',party:$('#record-party').value.trim(),amount,date:$('#record-date').value,due:$('#record-due').value,paidAmount,status,notes:$('#record-notes').value.trim(),createdAt:existing?.createdAt||new Date().toISOString()};if(id){records=records.map(r=>r.id===id?record:r);sync('update',{record});toast('Record updated');}else{records.push(record);sync('create',{record});toast(`${typeName(type)} saved`);}$('#record-dialog').close();save();});
$('#contact-form').addEventListener('submit',e=>{e.preventDefault();const contact={id:crypto.randomUUID(),name:$('#contact-name').value.trim(),type:$('#contact-type').value,phone:$('#contact-phone').value.trim(),email:$('#contact-email').value.trim()};contacts.push(contact);save();sync('createContact',{contact});$('#contact-dialog').close();toast('Contact saved');});
$('#login-form').addEventListener('submit',e=>{e.preventDefault();const role=$('#login-role').value,a=accounts[role];if($('#login-username').value.trim()===a.username&&$('#login-password').value===a.password){currentUser={role,label:a.label};sessionStorage.setItem(sessionKey,JSON.stringify(currentUser));$('#login-error').textContent='';updateLogin();}else $('#login-error').textContent='Incorrect account type, username, or password.';});
function updateLogin(){const signed=!!currentUser;$('#login-screen').classList.toggle('hidden',signed);$('#app-shell').classList.toggle('hidden',!signed);$$('[data-admin-only]').forEach(el=>el.classList.toggle('hidden',currentUser?.role!=='admin'));if(signed){$('#user-chip').textContent=currentUser.label;pullAll();}render();}
$$('.nav-link').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));$('.brand').addEventListener('click',event=>{event.preventDefault();showView('dashboard');});window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'dashboard',false));$$('[data-new]').forEach(btn=>btn.addEventListener('click',()=>openRecord(btn.dataset.new)));$('#add-record').addEventListener('click',()=>{const view=$('.nav-link.active').dataset.view;openRecord(view==='expenses'?'expense':view.slice(0,-1));});$('#add-contact').addEventListener('click',()=>{$('#contact-form').reset();$('#contact-dialog').showModal();});
$$('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>$('#record-dialog').close()));$$('[data-close-contact]').forEach(b=>b.addEventListener('click',()=>$('#contact-dialog').close()));$$('[data-close-sheet]').forEach(b=>b.addEventListener('click',()=>$('#sheet-dialog').close()));
$$('.dashboard-link').forEach(card=>{card.addEventListener('click',()=>showView(card.dataset.go));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();showView(card.dataset.go);}});});
document.addEventListener('click',e=>{const id=e.target.dataset.edit||e.target.dataset.delete||e.target.dataset.paid;if(!id)return;if(e.target.dataset.edit)editRecord(id);if(e.target.dataset.delete&&currentUser?.role==='admin'){records=records.filter(r=>r.id!==id);save();sync('delete',{id});toast('Record deleted');}if(e.target.dataset.paid&&currentUser?.role==='admin'){const r=records.find(x=>x.id===id);if(r){r.paidAmount=r.amount;r.status='paid';save();sync('update',{record:r});toast('Marked as paid');}}});
$$('.search-input,.filter-select').forEach(input=>input.addEventListener('input',render));$('[data-category-filter]').innerHTML='<option value="">All categories</option>'+categories.map(c=>`<option>${c}</option>`).join('');$$('[data-export]').forEach(b=>b.addEventListener('click',()=>exportCsv(b.dataset.export)));$('#export-report').addEventListener('click',()=>exportCsv('report'));$('#print-report').addEventListener('click',()=>window.print());
$('#import-records').addEventListener('click',()=>{ $('#import-file').dataset.type=''; $('#import-file').click(); });$$('[data-import-type]').forEach(button=>button.addEventListener('click',()=>{ $('#import-file').dataset.type=button.dataset.importType; $('#import-file').click(); }));$('#import-file').addEventListener('change',event=>{const file=event.target.files[0];if(file)importRecords(file,event.target.dataset.type||'');event.target.value='';});
$('#sign-out').addEventListener('click',()=>{sessionStorage.removeItem(sessionKey);currentUser=null;$('#login-form').reset();updateLogin();});$('#sheet-settings').addEventListener('click',()=>{$('#sheet-token').value=token();$('#sheet-error').textContent='';$('#sheet-dialog').showModal();});$('#sheet-form').addEventListener('submit',async e=>{e.preventDefault();localStorage.setItem(googleTokenKey,$('#sheet-token').value.trim());const result=await pullAll();if(result.ok){$('#sheet-dialog').close();toast('Google Sheet connected');}else $('#sheet-error').textContent=`Could not connect: ${result.message}`;});
$('#today').textContent=new Date().toLocaleDateString('en-KE',{weekday:'long',day:'numeric',month:'long',year:'numeric'});updateLogin();showView(location.hash.slice(1)||'dashboard',false);setInterval(()=>{if(currentUser&&token())pullAll(true);},10000);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
