/**
 * SARMART INVESTIMENTS online transaction service.
 * Admin alone uses API_TOKEN. Assistant accounts receive a limited session
 * token after signing in; they never receive the Sheet connection token.
 */
const API_TOKEN = 'Sarmart_2026!xR7kP2vN9mQ4zL8tH5wC';
const LEGACY_RECORDS_SHEET = 'Transactions';
const RECEIVABLES_SHEET = 'Receivables';
const PAYABLES_SHEET = 'Payables';
const EXPENSES_SHEET = 'Expenses';
const CONTACTS_SHEET = 'Contacts';
const STOCK_SHEET = 'Out of stock';
const USERS_SHEET = 'App users';
const NOTIFICATIONS_SHEET = 'App notifications';
const HEADERS = ['id', 'type', 'name', 'category', 'party', 'amount', 'paidAmount', 'payments', 'status', 'date', 'time', 'due', 'notes', 'noteEntries', 'enteredBy', 'color', 'createdAt'];
const CONTACT_HEADERS = ['id', 'name', 'type', 'phone', 'email', 'createdAt'];
const STOCK_HEADERS = ['id', 'name', 'date', 'remaining', 'photo', 'replaced', 'replacedDate', 'createdAt'];
const USER_HEADERS = ['id', 'username', 'passwordHash', 'role', 'active', 'createdAt'];
const NOTIFICATION_HEADERS = ['id', 'message', 'createdAt'];
const SESSION_VERSION_KEY = 'sarmart_session_version';
const SESSION_PREFIX = 'sarmart_user_session_';
const PASSWORD_SALT_KEY = 'sarmart_password_salt';
const RECORDS_MIGRATION_KEY = 'sarmart_records_split_v1';

function doGet(e) { return handle_(e.parameter || {}); }
function doPost(e) { try { return handle_(JSON.parse((e.postData && e.postData.contents) || '{}')); } catch (error) { return output_({ ok: false, error: 'Invalid request body.' }); } }
function handle_(request) { try { const action = request.action || 'list'; if (action === 'login') return output_({ ok: true, data: login_(request.username, request.password) }); const actor = authorize_(request); if (!actor) return output_({ ok: false, error: 'Unauthorized' }); if (!allowed_(actor, action)) return output_({ ok: false, error: 'Not allowed for this account.' }); return output_({ ok: true, data: dispatch_(action, request, actor) }); } catch (error) { return output_({ ok: false, error: error.message || 'Request failed.' }); } }
function dispatch_(action, request, actor) { if (action === 'list') return listRecords_(); if (action === 'listContacts') return listContacts_(); if (action === 'listStock') return listStock_(); if (action === 'listNotifications') return listNotifications_(); if (action === 'getSessionVersion') return { version: sessionVersion_() }; if (action === 'create') { const r=createRecord_(request.record); logAssistant_(actor, `${actor.username} added a ${r.type} entry for ${r.party||r.name||'an account'}`); return r; } if (action === 'update') { const r=updateRecord_(request.record); logAssistant_(actor, `${actor.username} edited a ${r.type} entry for ${r.party||r.name||'an account'}`); return r; } if (action === 'delete') return deleteRecord_(request.id); if (action === 'deleteMany') return deleteRecords_(request.ids); if (action === 'dedupeExactPayables') return dedupeExactRecords_('payable'); if (action === 'dedupeExactReceivables') return dedupeExactRecords_('receivable'); if (action === 'createContact') return createContact_(request.contact); if (action === 'createStock') { const r=createStock_(request.item); logAssistant_(actor, `${actor.username} added Out-of-Stock item ${r.name}`); return r; } if (action === 'updateStock') { const r=updateStock_(request.item); logAssistant_(actor, `${actor.username} edited Out-of-Stock item ${r.name}`); return r; } if (action === 'deleteStock') return deleteStock_(request.item && request.item.id); if (action === 'deleteAllStock') return deleteAllStock_(); if (action === 'createUser') return createUser_(request.user); if (action === 'deleteUser') return deleteUser_(request.id); if (action === 'listUsers') return listUsers_().map(user => ({ id: user.id, username: user.username, role: user.role, active: user.active })); if (action === 'logoutOtherDevices') return rotateSessionVersion_(); throw new Error('Unknown action'); }
function allowed_(actor, action) { if (actor.role === 'admin') return true; const normal = ['list', 'listContacts', 'listStock', 'getSessionVersion', 'create', 'update', 'createContact', 'createStock', 'updateStock']; const stock = ['listStock', 'getSessionVersion', 'createStock', 'updateStock']; return (actor.role === 'assistant' ? normal : stock).includes(action); }
function authorize_(request) { if (request.token === API_TOKEN) return { role: 'admin', username: 'sam' }; const session = request.session; if (!session) return null; const raw = PropertiesService.getScriptProperties().getProperty(SESSION_PREFIX + session); if (!raw) return null; const data = JSON.parse(raw); if (data.expiresAt < Date.now() || data.version !== sessionVersion_()) { PropertiesService.getScriptProperties().deleteProperty(SESSION_PREFIX + session); return null; } return { id: data.id, username: data.username, role: data.role }; }
function login_(username, password) { if (!username || !password) throw new Error('Username and password are required.'); const user = listUsers_().find(entry => entry.active && entry.username.toLowerCase() === String(username).trim().toLowerCase()); if (!user || user.passwordHash !== passwordHash_(password)) throw new Error('Incorrect username or password.'); const session = Utilities.getUuid().replace(/-/g, '') + Utilities.getUuid().replace(/-/g, ''); const data = { id: user.id, username: user.username, role: user.role, version: sessionVersion_(), expiresAt: Date.now() + 1000 * 60 * 60 * 24 * 30 }; PropertiesService.getScriptProperties().setProperty(SESSION_PREFIX + session, JSON.stringify(data)); return { session: session, username: user.username, role: user.role, sessionVersion: data.version }; }
function createUser_(user) { if (!user || !user.username || !user.password || !['assistant', 'stock'].includes(user.role)) throw new Error('Enter an assistant username, password, and role.'); const username = String(user.username).trim(); if (username.length < 3 || String(user.password).length < 3) throw new Error('Username and password must have at least 3 characters.'); if (listUsers_().some(entry => entry.username.toLowerCase() === username.toLowerCase())) throw new Error('That username is already in use.'); const entry = { id: Utilities.getUuid(), username: username, passwordHash: passwordHash_(user.password), role: user.role, active: true, createdAt: new Date().toISOString() }; const sheet = usersSheet_(); sheet.appendRow(USER_HEADERS.map(header => entry[header] ?? '')); return { id: entry.id, username: entry.username, role: entry.role, active: true }; }
function listUsers_() { const values = usersSheet_().getDataRange().getValues(); if (values.length < 2) return []; const headers = values.shift(); return values.map(row => Object.fromEntries(headers.map((header, index) => [header, row[index] ?? '']))).map(user => ({ ...user, active: String(user.active).toLowerCase() === 'true' })); }
function passwordHash_(password) { const props = PropertiesService.getScriptProperties(); let salt = props.getProperty(PASSWORD_SALT_KEY); if (!salt) { salt = Utilities.getUuid(); props.setProperty(PASSWORD_SALT_KEY, salt); } const bytes = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, salt + String(password), Utilities.Charset.UTF_8); return bytes.map(byte => ('0' + (byte & 0xFF).toString(16)).slice(-2)).join(''); }
function output_(data) { return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON); }
function sessionVersion_() { return PropertiesService.getScriptProperties().getProperty(SESSION_VERSION_KEY) || '1'; }
function rotateSessionVersion_() { const version = String(Date.now()); PropertiesService.getScriptProperties().setProperty(SESSION_VERSION_KEY, version); return { version: version }; }
function recordSheet_(type) { const name = type === 'receivable' ? RECEIVABLES_SHEET : type === 'payable' ? PAYABLES_SHEET : type === 'expense' ? EXPENSES_SHEET : ''; if (!name) throw new Error('Unknown transaction type.'); return ensureSheet_(name, HEADERS); }
function recordSheets_() { return [recordSheet_('receivable'), recordSheet_('payable'), recordSheet_('expense')]; }
function migrateLegacyRecords_() { const props = PropertiesService.getScriptProperties(); if (props.getProperty(RECORDS_MIGRATION_KEY)) return; const spreadsheet = SpreadsheetApp.getActiveSpreadsheet(), legacy = spreadsheet.getSheetByName(LEGACY_RECORDS_SHEET); if (!legacy || legacy.getLastRow() < 2) { props.setProperty(RECORDS_MIGRATION_KEY, 'done'); return; } const entries = rows_(legacy); entries.forEach(record => { if (!['receivable', 'payable', 'expense'].includes(record.type)) return; const target = recordSheet_(record.type); if (record.id && findRow_(target, record.id) >= 2) return; target.appendRow(HEADERS.map(header => serialize_(record[header]))); }); legacy.deleteRows(2, legacy.getLastRow() - 1); props.setProperty(RECORDS_MIGRATION_KEY, 'done'); }
function contactsSheet_() { return ensureSheet_(CONTACTS_SHEET, CONTACT_HEADERS); }
function stockSheet_() { return ensureSheet_(STOCK_SHEET, STOCK_HEADERS); }
function usersSheet_() { return ensureSheet_(USERS_SHEET, USER_HEADERS); }
function notificationsSheet_() { return ensureSheet_(NOTIFICATIONS_SHEET, NOTIFICATION_HEADERS); }
function ensureSheet_(name, headers) { const spreadsheet = SpreadsheetApp.getActiveSpreadsheet(); let sheet = spreadsheet.getSheetByName(name); if (!sheet) { sheet = spreadsheet.insertSheet(name); sheet.appendRow(headers); sheet.setFrozenRows(1); } else { const existing = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0]; headers.filter(header => !existing.includes(header)).forEach(header => sheet.getRange(1, sheet.getLastColumn() + 1).setValue(header)); } return sheet; }
function serialize_(value) { return value && typeof value === 'object' ? JSON.stringify(value) : value ?? ''; }
function rows_(sheet) { const values = sheet.getDataRange().getValues(); if (values.length < 2) return []; const headers = values.shift(); return values.map(row => Object.fromEntries(headers.map((header, index) => [header, row[index] ?? '']))); }
function findRows_(sheet, id) { const count = sheet.getLastRow() - 1; if (count < 1) return []; return sheet.getRange(2, 1, count, 1).getValues().flat().map((value, index) => String(value) === String(id) ? index + 2 : 0).filter(Boolean); }
function findRow_(sheet, id) { return findRows_(sheet, id)[0] || -1; }
function removeDuplicateRows_(sheet, rows) { rows.slice(1).sort((a, b) => b - a).forEach(row => sheet.deleteRow(row)); }
function listRecords_() { migrateLegacyRecords_(); return recordSheets_().flatMap(rows_); }
function createRecord_(record) { if (!record || !record.id || !record.type || !Number.isFinite(Number(record.amount)) || !record.date) throw new Error('Missing transaction details.'); const lock = LockService.getScriptLock(); lock.waitLock(30000); try { const sheet = recordSheet_(record.type), matchingRows = findRows_(sheet, record.id), existingRow = matchingRows[0] || -1, headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0], values = { ...record, createdAt: record.createdAt || new Date().toISOString() }; if (existingRow >= 2) { const old = Object.fromEntries(headers.map((header, i) => [header, sheet.getRange(existingRow, i + 1).getValue()])); sheet.getRange(existingRow, 1, 1, headers.length).setValues([headers.map(header => serialize_({ ...old, ...values }[header]))]); removeDuplicateRows_(sheet, matchingRows); return record; } sheet.appendRow(headers.map(header => serialize_(values[header]))); return record; } finally { lock.releaseLock(); } }
function updateRecord_(record) { if (!record || !record.id || !record.type) throw new Error('Missing transaction details.'); const lock = LockService.getScriptLock(); lock.waitLock(30000); try { const sheet = recordSheet_(record.type), matchingRows = findRows_(sheet, record.id), row = matchingRows[0] || -1; if (row < 2) throw new Error('Transaction not found.'); const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0], old = Object.fromEntries(headers.map((header, i) => [header, sheet.getRange(row, i + 1).getValue()])), values = { ...old, ...record }; sheet.getRange(row, 1, 1, headers.length).setValues([headers.map(header => serialize_({ ...old, ...values }[header]))]); removeDuplicateRows_(sheet, matchingRows); return record; } finally { lock.releaseLock(); } }
function deleteRecord_(id) { for (const sheet of recordSheets_()) { const rows = findRows_(sheet, id); if (rows.length) { rows.sort((a, b) => b - a).forEach(row => sheet.deleteRow(row)); return { id: id }; } } throw new Error('Transaction not found.'); }
function deleteRecords_(ids) { if (!Array.isArray(ids) || !ids.length) return { count: 0 }; const wanted = new Set(ids); let count = 0; recordSheets_().forEach(sheet => { const rows = sheet.getLastRow() > 1 ? sheet.getRange(2, 1, sheet.getLastRow() - 1, 1).getValues().flat() : [], targets = rows.map((id, index) => wanted.has(id) ? index + 2 : 0).filter(Boolean).sort((a,b) => b-a); targets.forEach(row => sheet.deleteRow(row)); count += targets.length; }); return { count: count }; }
function dedupeExactRecords_(type) { migrateLegacyRecords_(); const lock = LockService.getScriptLock(); lock.waitLock(30000); try { const sheet = recordSheet_(type), headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0], rowCount = sheet.getLastRow() - 1, values = rowCount > 0 ? sheet.getRange(2, 1, rowCount, headers.length).getValues() : [], keyColumns = headers.map((header, index) => header !== 'id' && header !== 'createdAt' ? index : -1).filter(index => index >= 0), seen = new Set(), kept = []; values.forEach(row => { const key = keyColumns.map(column => String(row[column] ?? '').trim()).join('\u001f'); if (!seen.has(key)) { seen.add(key); kept.push(row); } }); const removed = values.length - kept.length; if (removed) { sheet.getRange(2, 1, rowCount, headers.length).clearContent(); if (kept.length) sheet.getRange(2, 1, kept.length, headers.length).setValues(kept); if (rowCount > kept.length) sheet.deleteRows(kept.length + 2, rowCount - kept.length); } return { type: type, removed: removed, remaining: kept.length }; } finally { lock.releaseLock(); } }
function listContacts_() { return rows_(contactsSheet_()); }
function createContact_(contact) { if (!contact || !contact.id || !contact.name) throw new Error('Missing contact details.'); const sheet = contactsSheet_(), headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0], values = { ...contact, createdAt: new Date().toISOString() }; sheet.appendRow(headers.map(header => serialize_(values[header]))); return contact; }
function listStock_() { return rows_(stockSheet_()); }
function listNotifications_() { return rows_(notificationsSheet_()).slice(-30).reverse(); }
function logAssistant_(actor, message) { if (actor.role === 'admin') return; notificationsSheet_().appendRow([Utilities.getUuid(), message, new Date().toISOString()]); }
function createStock_(item) { if (!item || !item.id || !item.name || !item.date) throw new Error('Missing out-of-stock item details.'); const sheet = stockSheet_(), headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0], values = { ...item, createdAt: new Date().toISOString() }; sheet.appendRow(headers.map(header => serialize_(values[header]))); return item; }
function updateStock_(item) { if (!item || !item.id) throw new Error('Missing out-of-stock item ID.'); const sheet = stockSheet_(), row = findRow_(sheet, item.id); if (row < 2) throw new Error('Out-of-stock item not found.'); const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0], old = Object.fromEntries(headers.map((header, i) => [header, sheet.getRange(row, i + 1).getValue()])), values = { ...old, ...item }; sheet.getRange(row, 1, 1, headers.length).setValues([headers.map(header => serialize_(values[header]))]); return item; }
function deleteStock_(id) { if (!id) throw new Error('Missing out-of-stock item ID.'); const sheet = stockSheet_(), row = findRow_(sheet, id); if (row < 2) throw new Error('Out-of-stock item not found.'); sheet.deleteRow(row); return { id: id }; }
function deleteAllStock_() { const sheet = stockSheet_(), count = sheet.getLastRow() - 1; if (count > 0) sheet.deleteRows(2, count); return { count: count }; }
function deleteUser_(id) { if (!id) throw new Error('Missing assistant ID.'); const sheet = usersSheet_(), row = findRow_(sheet, id); if (row < 2) throw new Error('Assistant login not found.'); sheet.deleteRow(row); rotateSessionVersion_(); return { id: id }; }
